In [1]:
import numpy as np
from math import factorial

In [2]:
np.set_printoptions(precision=4)

In [3]:
M = 4
lambda_0 = 3.5

In [4]:
def calc_rho(m, mu, alpha):
    return alpha * lambda_0 / mu

In [5]:
def calc_p0(m, rho):
    if m == 1:
        return 1 - rho
    else:
        p0 = 1
        for i in np.arange(1, m + 1):
            p0 += rho ** i / factorial(i)
        p0 += rho ** (m + 1) / factorial(m) / (m - rho)
        return 1 / p0

In [6]:
def calc_l(m, p0, rho):
    if m == 1:
        return rho ** 2 / (1 - rho)
    else:
        return p0 * rho ** (m + 1) / m / (1 - rho / m) ** 2 / factorial(m)

In [7]:
def calc_n(m, l, rho):
    if m == 1:
        return l
    else:
        return l + rho

In [8]:
def calc_to(m, p0, rho, mu):
    if m == 1:
        return rho / (1 - rho)
    else:
        return p0 * rho ** m / m / mu / factorial(m) / (1 - rho / m) ** 2

In [9]:
def calc_t(m, to, mu, alpha):
    if m == 1:
        return 1 / (mu - alpha * lambda_0)
    else:
        return to + 1 / mu

In [10]:
def calc_system(m, mu, alpha):
    rho = calc_rho(m, mu, alpha)
    p0 = calc_p0(m, rho)
    l = calc_l(m, p0, rho)
    n = calc_n(m, l, rho)
    to = calc_to(m, p0, rho, mu)
    t = calc_t(m, to, mu, alpha)
    return (l, n, to, t)

In [11]:
m = np.array([2, 1, 2, 2])
mu = np.array([10, 3, 7, 7])
alpha = np.array([4/3, 56/297, 119/297, 56/297])

In [12]:
l = np.zeros(M)
n = np.zeros(M)
to = np.zeros(M)
t = np.zeros(M)

## Расчет узлов системы

In [13]:
for i in range(M):
    (l[i], n[i], to[i], t[i]) = calc_system(m[i], mu[i], alpha[i])

In [14]:
n, l, t, to

(array([0.4935, 0.062 , 0.2024, 0.0945]),
 array([0.0269, 0.062 , 0.002 , 0.0002]),
 array([0.1058, 0.4273, 0.1443, 0.1432]),
 array([0.0058, 0.282 , 0.0014, 0.0003]))

## Расчет все сети

In [15]:
np.array([n.sum(), l.sum(), np.multiply(alpha, t).sum(), np.multiply(alpha, to).sum()])

array([0.8524, 0.0911, 0.3064, 0.0615])